In [1]:
##
import torch
from torch.utils.data import Dataset
help(Dataset)
class MyDataset(Dataset):
    # 构造函数
    def __init__(self, data_tensor, target_tensor):
        self.data_tensor = data_tensor
        self.target_tensor = target_tensor
    # 返回数据集大小
    def __len__(self):
        return self.data_tensor.size(0)
    # 返回索引的数据与标签
    def __getitem__(self, index):
        return self.data_tensor[index], self.target_tensor[index]

Help on class Dataset in module torch.utils.data.dataset:

class Dataset(typing.Generic)
 |  An abstract class representing a :class:`Dataset`.
 |  
 |  All datasets that represent a map from keys to data samples should subclass
 |  it. All subclasses should overwrite :meth:`__getitem__`, supporting fetching a
 |  data sample for a given key. Subclasses could also optionally overwrite
 |  :meth:`__len__`, which is expected to return the size of the dataset by many
 |  :class:`~torch.utils.data.Sampler` implementations and the default options
 |  of :class:`~torch.utils.data.DataLoader`.
 |  
 |  .. note::
 |    :class:`~torch.utils.data.DataLoader` by default constructs a index
 |    sampler that yields integral indices.  To make it work with a map-style
 |    dataset with non-integral indices/keys, a custom sampler must be provided.
 |  
 |  Method resolution order:
 |      Dataset
 |      typing.Generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __add__(self, oth

In [2]:
Dataset??

In [3]:

# 生成数据
data_tensor = torch.randn(10, 3)
target_tensor = torch.randint(2, (10,)) # 标签是0或1
print(data_tensor)

print(target_tensor)

# 将数据封装成Dataset
my_dataset = MyDataset(data_tensor, target_tensor)

# 查看数据集大小
print('Dataset size:', len(my_dataset))
'''
输出：
Dataset size: 10
'''

# 使用索引调用数据
print('tensor_data[0]: ', my_dataset[0])
'''
输出:
tensor_data[0]:  (tensor([ 0.4931, -0.0697,  0.4171]), tensor(0))
'''

tensor([[-1.0744, -0.6722,  0.7930],
        [ 0.6547,  1.0699, -0.2508],
        [-1.1732,  0.3434,  1.2260],
        [-1.0856, -1.1031,  0.4689],
        [-0.4403, -1.1497, -0.2286],
        [ 0.1182,  0.3150, -0.4138],
        [-2.1027,  1.5216, -1.8243],
        [-0.1909,  1.1578,  0.0276],
        [-0.5883, -1.0077, -1.0088],
        [ 0.3126,  1.1999, -0.4394]])
tensor([0, 1, 1, 0, 1, 1, 1, 0, 0, 1])
Dataset size: 10
tensor_data[0]:  (tensor([-1.0744, -0.6722,  0.7930]), tensor(0))


'\n输出:\ntensor_data[0]:  (tensor([ 0.4931, -0.0697,  0.4171]), tensor(0))\n'

In [4]:

from torch.utils.data import DataLoader
tensor_dataloader = DataLoader(dataset=my_dataset, # 传入的数据集, 必须参数
                               batch_size=2,       # 输出的batch大小
                               shuffle=True,       # 数据是否打乱
                               num_workers=0)      # 进程数, 0表示只有主进程

# 以循环形式输出
for data, target in tensor_dataloader: 
    print(data, target)
'''
输出:
tensor([[-0.1781, -1.1019, -0.1507],
        [-0.6170,  0.2366,  0.1006]]) tensor([0, 0])
tensor([[ 0.9451, -0.4923, -1.8178],
        [-0.4046, -0.5436, -1.7911]]) tensor([0, 0])
tensor([[-0.4561, -1.2480, -0.3051],
        [-0.9738,  0.9465,  0.4812]]) tensor([1, 0])
tensor([[ 0.0260,  1.5276,  0.1687],
        [ 1.3692, -0.0170, -1.6831]]) tensor([1, 0])
tensor([[ 0.0515, -0.8892, -0.1699],
        [ 0.4931, -0.0697,  0.4171]]) tensor([1, 0])
'''
 
# 输出一个batch
print('One batch tensor data: ', iter(tensor_dataloader).next())
'''
输出:
One batch tensor data:  [tensor([[ 0.9451, -0.4923, -1.8178],
        [-0.4046, -0.5436, -1.7911]]), tensor([0, 0])]
'''

tensor([[ 0.1182,  0.3150, -0.4138],
        [-0.5883, -1.0077, -1.0088]]) tensor([1, 0])
tensor([[ 0.6547,  1.0699, -0.2508],
        [-1.1732,  0.3434,  1.2260]]) tensor([1, 1])
tensor([[ 0.3126,  1.1999, -0.4394],
        [-0.1909,  1.1578,  0.0276]]) tensor([1, 0])
tensor([[-1.0856, -1.1031,  0.4689],
        [-1.0744, -0.6722,  0.7930]]) tensor([0, 0])
tensor([[-0.4403, -1.1497, -0.2286],
        [-2.1027,  1.5216, -1.8243]]) tensor([1, 1])
One batch tensor data:  [tensor([[-1.0744, -0.6722,  0.7930],
        [-2.1027,  1.5216, -1.8243]]), tensor([0, 1])]


'\n输出:\nOne batch tensor data:  [tensor([[ 0.9451, -0.4923, -1.8178],\n        [-0.4046, -0.5436, -1.7911]]), tensor([0, 0])]\n'

In [5]:
## torchvision 使用

# 以MNIST为例
import torchvision
mnist_dataset = torchvision.datasets.MNIST(root='./data',
                                       train=True,
                                       transform=None,
                                       target_transform=None,
                                       download=True)

2.5%

31.0%IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

100.0%


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw



102.8%


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw



100.0%


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw



112.7%

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw



In [6]:

mnist_dataset_list = list(mnist_dataset)
print(mnist_dataset_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [7]:

display(mnist_dataset_list[0][0])
print("Image label is:", mnist_dataset_list[0][1])

Image label is: 5
